import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Components
import Footer from "./ui/footer/Footer"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bus Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Footer footerColor="--main-color"/>
        </body>
    </html>
  );
}
